# Generated by Django 4.2.3 on 2023-07-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingRooms', '0002_alter_room_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
    ]
